name: 使用抱脸创建域名面板

on:
  workflow_dispatch:
    inputs:
      Token:
        description: 'Hugging Face Token（需要写权限）'
        required: true
      image:
        description: 'Docker 镜像地址'
        required: false
        default: ''
      password:
        description: '管理员密码'
        required: true
      database_url:
        description: 'Neon数据库连接字符串'
        required: true
      cf_key:
        description: 'Cloudflare API Token'
        required: false
        default: ''
      tg_bot_token:
        description: 'Telegram 机器人 Token'
        required: false
        default: ''
      tg_user_id:
        description: 'Telegram Chat ID'
        required: false
        default: ''
      wechat_sendkey:
        description: '微信Server酱'
        required: false
        default: ''
      qmsg_key:
        description: 'Qmsg酱 Key'
        required: false
        default: ''
      qmsg_qq:
        description: 'Qmsg酱 接收QQ'
        required: false
        default: ''
      webdav_url:
        description: 'WebDAV 地址'
        required: false
        default: ''
      webdav_user:
        description: 'WebDAV 用户名'
        required: false
        default: ''
      webdav_pass:
        description: 'WebDAV 密码'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 隐藏输入信息
        uses: levibostian/action-hide-sensitive-inputs@v1

      - name: 安装 Python 依赖
        run: |
          python -m pip install --upgrade pip wheel
          pip install huggingface_hub

      - name: 运行脚本（domain.py）
        run: |
          python notes/domain.py \
            --token "${{ github.event.inputs.Token }}" \
            --image "${{ github.event.inputs.image }}" \
            --password "${{ github.event.inputs.password }}" \
            --database-url "${{ github.event.inputs.database_url }}" \
            --cf-key "${{ github.event.inputs.cf_key }}" \
            --tg-bot-token "${{ github.event.inputs.tg_bot_token }}" \
            --tg-user-id "${{ github.event.inputs.tg_user_id }}" \
            --wechat-sendkey "${{ github.event.inputs.wechat_sendkey }}" \
            --qmsg-key "${{ github.event.inputs.qmsg_key }}" \
            --qmsg-qq "${{ github.event.inputs.qmsg_qq }}" \
            --webdav-url "${{ github.event.inputs.webdav_url }}" \
            --webdav-user "${{ github.event.inputs.webdav_user }}" \
            --webdav-pass "${{ github.event.inputs.webdav_pass }}"


